# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0adb1f955dbb3150b7b49a08c2d6dca0033942e7c065d89782ada2c79bca946ae206afd4868190ac5dbc9cf33813e8d103ee8c03281f68e555c7676301912d5

test:
  secret_key_base: d2e8a2a3ab845635918040e49ea0ec4d7ce1851821fb0bcb6e08ea77c0c6f39d75385ae35f12d41ee13307bd498efb695520257a952c841b402d946387e5b436

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
